return {
	name="Original Level Pack",
	author="DJ Omnimaga",
	spritesheet="sprites.png",
	count=16,
	{
		name = "Level 1",
		seed = 1,
		rndintrv = 5,
		slope = 5,
		minheight = 4,
		maxheight = 5,
		time = 100,
		bgspr = {7},
		wallspr = {3,4,5,6},
		ballspr = {29},
		length = 256,
		scrollspeed = 4
	},
	{
		name = "Level 2",
		seed = 2,
		rndintrv = 16,
		slope = 4,
		minheight = 5,
		maxheight = 16,
		time = 100,
		bgspr = {19},
		wallspr = {2},
		ballspr = {29},
		length = 256,
		scrollspeed = 2
	},
	{
		name = "Level 3",
		seed = 3,
		rndintrv = 1,
		slope = 8,
		minheight = 4,
		maxheight = 5,
		time = 100,
		bgspr = {22},
		wallspr = {1},
		ballspr = {29},
		length = 256,
		scrollspeed = 3
	},
	{
		name = "Level 4",
		seed = 4,
		rndintrv = 4,
		slope = 4,
		minheight = 5,
		maxheight = 8,
		time = 60,
		bgspr = {19,20},
		wallspr = {23,24,25,26},
		ballspr = {29},
		length = 256,
		scrollspeed = 3
	},
	{
		name = "Level 5",
		seed = 5,
		rndintrv = 50,
		slope = 50,
		minheight = 5,
		maxheight = 20,
		time = 36,
		bgspr = {1},
		wallspr = {16},
		ballspr = {29},
		length = 256,
		scrollspeed = 1
	},
	{
		name = "Level 6",
		seed = 6,
		rndintrv = 8,
		slope = 2,
		minheight = 5,
		maxheight = 9,
		time = 100,
		bgspr = {11,12,13,14},
		wallspr = {13,14,11,12},
		ballspr = {29},
		length = 256,
		scrollspeed = 1
	},
	{
		name = "Level 7",
		seed = 7,
		rndintrv = 8,
		slope = 2,
		minheight = 4,
		maxheight = 5,
		time = 150,
		bgspr = {8},
		wallspr = {0},
		ballspr = {29},
		length = 256,
		scrollspeed = 2
	},
	{
		name = "Level 8",
		seed = 8,
		rndintrv = 1,
		slope = 3,
		minheight = 4,
		maxheight = 5,
		time = 100,
		bgspr = {16},
		wallspr = {15},
		ballspr = {29},
		length = 256,
		scrollspeed = 8
	},
	{
		name = "Level 9",
		seed = 9,
		rndintrv = 1,
		slope = 4,
		minheight = 5,
		maxheight = 6,
		time = 70,
		bgspr = {22},
		wallspr = {7},
		ballspr = {29},
		length = 256,
		scrollspeed = 3
	},
	{
		name = "Level 10",
		seed = 10,
		rndintrv = 2,
		slope = 2,
		minheight = 5,
		maxheight = 6,
		time = 120,
		bgspr = {6,5,4,3},
		wallspr = {3,4,5,6},
		ballspr = {29},
		length = 256,
		scrollspeed = 2
	},
	{
		name = "Level 11",
		seed = 11,
		rndintrv = 2,
		slope = 1,
		minheight = 4,
		maxheight = 8,
		time = 320,
		bgspr = {10,11},
		wallspr = {21},
		ballspr = {29},
		length = 256,
		scrollspeed = 4
	},
	{
		name = "Level 12",
		seed = 12,
		rndintrv = 3,
		slope = 1,
		minheight = 4,
		maxheight = 3,
		time = 200,
		bgspr = {17,18,14,18},
		wallspr = {27},
		ballspr = {29},
		length = 256,
		scrollspeed = 3
	},
	{
		name = "Level 13",
		seed = 13,
		rndintrv = 1,
		slope = 1,
		minheight = 4,
		maxheight = 5,
		time = 100,
		bgspr = {7,14},
		wallspr = {4,8},
		ballspr = {29},
		length = 256,
		scrollspeed = 2
	},
	{
		name = "Level 14",
		seed = 14,
		rndintrv = 1,
		slope = 1,
		minheight = 5,
		maxheight = 6,
		time = 150,
		bgspr = {7,7,14,14},
		wallspr = {0,0,14,14},
		ballspr = {29},
		length = 256,
		scrollspeed = 2
	},
	{
		name = "Level 15",
		seed = 15,
		rndintrv = 50,
		slope = 1,
		minheight = 5,
		maxheight = 5,
		time = 300,
		bgspr = {16},
		wallspr = {8},
		ballspr = {29},
		length = 256,
		scrollspeed = 8
	},
	{
		name = "Level 16",
		seed = 16,
		rndintrv = 10,
		slope = 1,
		minheight = 5,
		maxheight = 5,
		time = 666,
		bgspr = {14},
		wallspr = {14,14,14,16},
		ballspr = {29},
		length = 256,
		scrollspeed = 1
	},
}